project:
  type: website


website:
  title: "Time Series Analysis"
  site-url: "https://YOUR_GH_USERNAME.github.io/time-series/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About You"
      - href: introduction.qmd
        text: Introduction
      - href: data-sources.qmd
        text: "Data Sources"
      - href: data-visualization.qmd
        text: "Data Visualization"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: univariate-ts-models.qmd
        text: "Univariate TS Models (ARIMA/SARIMA)"
      - href: multivariate-ts-models.qmd
        text: "Multivariate TS Models (ARIMAX/SARIMAX/VAR)"
      - href: financial-ts-models.qmd
        text: "Financial Time Series Models (ARCH/GARCH)"
      - href: deep-learning-ts.qmd
        text: "Deep Learning for TS"
      - href: other-topics.qmd
        text: "Other: Interrupted TS/ARFIMA/Spectral Analysis"
      - href: conclusions.qmd
        text: Conclusions

format:
  html:
    theme: lux   # pick any non-default theme from the Quarto themes page
